name: Make RPMs
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  make-rpm:
    runs-on: ubuntu-latest
    env:
      DEST_ID: core
      NSVER: 7
      DOCKER_IMAGE: nethserver/makerpms:7
      EVARS: |
        -e DEST_ID
        -e TRAVIS_BRANCH
        -e TRAVIS_BUILD_ID
        -e TRAVIS_PULL_REQUEST_BRANCH
        -e TRAVIS_PULL_REQUEST
        -e TRAVIS_REPO_SLUG
        -e TRAVIS_TAG
        -e NSVER
        -e VERSIONS_PACK
        -e STAGES_PACK
        -e UPLOAD_DEST
    steps:
      - uses: actions/checkout@v3
      - name: Prep Build
        run: ./prep-sources
      - name: Build RPM and publish
        run: |
          TRAVIS_BRANCH="${{ github.ref_name }}"
          TRAVIS_BUILD_ID="${{ github.run_id }}"
          TRAVIS_PULL_REQUEST_BRANCH="${{ github.base_ref }}"
          TRAVIS_PULL_REQUEST=$(echo "${{ github.ref }}" | sed -n "s/^refs\/pull\/\(.*\)\/merge$/\1/p")
          TRAVIS_REPO_SLUG="${{ github.action_repository }}"
          TRAVIS_TAG=$(echo "${{ github.ref }}" | sed -n "s/^refs\/tag\/\(.*\)$/\1/p")
          echo "Hello $TRAVIS_PULL_REQUEST"
