name: Make RPMs
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  make-rpm:
    runs-on: ubuntu-latest
    env:
      DEST_ID: core
      NSVER: 7
      DOCKER_IMAGE: nethserver/makerpms:7
      EVARS: |
        -e DEST_ID
        -e TRAVIS_BRANCH
        -e TRAVIS_BUILD_ID
        -e TRAVIS_PULL_REQUEST_BRANCH
        -e TRAVIS_PULL_REQUEST
        -e TRAVIS_REPO_SLUG
        -e TRAVIS_TAG
        -e NSVER
        -e VERSIONS_PACK
        -e STAGES_PACK
        -e UPLOAD_DEST
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prep Build
        run: ./prep-sources
      - name: Build RPM and publish
        run: |
          export TRAVIS_BRANCH="$GITHUB_BASE_REF"
          export TRAVIS_BUILD_ID="${GITHUB_RUN_ID}"
          export TRAVIS_PULL_REQUEST_BRANCH="${GITHUB_HEAD_REF}"
          export TRAVIS_PULL_REQUEST=$(echo "${GITHUB_REF}" | sed -n "s/^refs\/pull\/\(.*\)\/merge$/\1/p")
          export TRAVIS_REPO_SLUG="${GITHUB_ACTION_REPOSITORY}"
          export TRAVIS_TAG=$(echo "${GITHUB_REF}" | sed -n "s/^refs\/tag\/\(.*\)$/\1/p")
          docker run --name makerpms ${EVARS} \
            --hostname ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}.nethserver.org \
            --volume $PWD:/srv/makerpms/src:ro ${DOCKER_IMAGE} makerpms-travis -s *.spec
          docker commit makerpms nethserver/build
          docker run ${EVARS} -e SECRET -e SECRET_URL -e AUTOBUILD_SECRET -e AUTOBUILD_SECRET_URL nethserver/build uploadrpms-travis
