name: Make RPMs
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  make-rpm:
    runs-on: ubuntu-latest
    env:
      DEST_ID: core
      NSVER: 7
      DOCKER_IMAGE: nethserver/makerpms:7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Generate .env file
        run: |
          cat .env < EOF
            DEST_ID=${{ env.DEST_ID }}
            NSVER=${{ env.NSVER }}
            DOCKER_IMAGE=${{ env.DOCKER_IMAGE }}
            GITHUB_HEAD_REF=${{ env.GITHUB_HEAD_REF }}
            GITHUB_RUN_NUMBER=${{ env.GITHUB_RUN_NUMBER }}
            GITHUB_ACTIONS=${{ env.GITHUB_ACTIONS }}
            ENDPOINTS_PACK=${{ secrets.endpoints_pack }}
            SECRET=${{ secrets.secret }}
            SECRET_URL=${{ secrets.secret_url }}
            AUTOBUILD_SECRET=${{ secrets.autobuild_secret }}
            AUTOBUILD_SECRET_URL=${{ secrets.autobuild_secret_url }}
            GPG_SIGN_KEY=${{ secrets.gpg_sign_key }}
          EOF
        run: if test -f "prep-sources"; then ./prep-sources; fi
      - name: Build RPM and publish
        run: |
          echo "Starting build..."
          docker run --name makerpms \
            --env-file .env
            --hostname $GITHUB_RUN_ID-$GITHUB_RUN_NUMBER.nethserver.org \
            --volume $PWD:/srv/makerpms/src:ro \
            $DOCKER_IMAGE \
            makerpms-github -s *.spec
          echo "Build succesful."
          echo "Checking if publish configuration exists..."
          if [[ "${{ secret.endpoints_pack }}" -a "${{ secret.secret }} ]]; then
            echo "Publish configuration exists, pushing package to repo."
            docker commit makerpms nethserver/build
            docker run \
              --env-file .env
              nethserver/build \
              uploadrpms-github
            echo "Publish complete."
          fi
